#!/usr/bin/env python3
"""Generate Android string resources from the JSON content export.

Run after `npm run export:content` so the Android chrome and the web app say
exactly the same things. Keys are camelCase in the export and snake_case in
Android resources.
"""
import json
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parent.parent
res = root / "android/app/src/main/res"


def resource_name(key: str) -> str:
    return "".join(f"_{c.lower()}" if c.isupper() else c for c in key)


def escape(value: str) -> str:
    # Order matters: ampersands first, or the entities get double-escaped.
    value = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return value.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"')


def main() -> int:
    for lang, outdir in (("en", "values"), ("ne", "values-ne")):
        src = root / f"content/strings-{lang}.json"
        if not src.exists():
            print(f"missing {src}; run npm run export:content first", file=sys.stderr)
            return 1
        data = json.loads(src.read_text(encoding="utf-8"))

        lines = [
            '<?xml version="1.0" encoding="utf-8"?>',
            f"<!-- Generated by scripts/gen-android-strings.py from content/strings-{lang}.json. Do not edit. -->",
            "<resources>",
        ]
        # "appName" maps to app_name, which is what the launcher shows.
        names = []
        for key, value in data.items():
            name = resource_name(key)
            names.append(name)
            lines.append(f'    <string name="{name}">{escape(value)}</string>')
        lines.append("</resources>")

        # A duplicate resource name is a hard build failure in AAPT, so catch
        # it here rather than several minutes into a Gradle build.
        duplicates = sorted({n for n in names if names.count(n) > 1})
        if duplicates:
            print(f"duplicate resource names: {duplicates}", file=sys.stderr)
            return 1
        if "app_name" not in names:
            print("no app_name string; the launcher label would be missing", file=sys.stderr)
            return 1

        out = res / outdir / "strings.xml"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"  {out.relative_to(root)}: {len(data) + 1} strings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
